name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      SERVER_2_HOST: ${{secrets.SERVER_2_HOST}}
      USERNAME: ${{secrets.USERNAME}}
    steps:
      - run: |
          hostname
