name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      SERVER_2_HOST: ${{secrets.SERVER_2_HOST}}
      USERNAME: ${{secrets.USERNAME}}
    steps:
      - run: |
          ssh-keyscan $SERVER_2_HOST >> ~/.ssh/known_hosts
          echo "$PRIVATE_KEY" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh -i ~/.ssh/github_actions $USERNAME@$SERVER_2_HOST "cd /docker-compose-flask-app && git pull && docker compose up -d --build"
